# gerado por rt1_r1_runtime_real.py
COMANDOS = ['Apaga o arquivo rt1_inexistente.txt.', 'tenta de novo']
ATRASO_INICIAL_S = 0.0
TIMEOUT_RESPOSTA_S = 90.0
TIMEOUT_VOZ_S = 30.0
INTERVALO_ENTRE_COMANDOS_S = 0.05
PARAR_SEM_RESPOSTA = True
ENCERRAR_AO_FINAL = True
SILENCIAR_VOZ_DURANTE_TESTE = True
AGUARDAR_CONFIRMACAO_EXECUCAO = True
EXPECTATIVAS_SEMANTICAS = {}
