"""Estado inicial da memória contextual compartilhada."""

from __future__ import annotations

from typing import Any, Dict

from mente_laylay.memoria_mental.continuidade_geral import estado_continuidade_geral_inicial
from mente_laylay.memoria_mental.consciencia_temporal import estado_temporal_inicial
from mente_laylay.memoria_mental.registro_semantico import estado_registro_semantico_inicial


def criar_estado_mental_inicial() -> Dict[str, Any]:
    return {
        "ultima_entrada": "",
        "ultima_entrada_ts": 0.0,
        "turno_atual": {},
        "plano_turno_atual": {},
        "avaliacoes_turno": [],
        "metricas_verificador": {},
        "trilha_decisoes_turno": [],
        "diagnostico_metricas": {},
        "diagnostico_prompts": {},
        "diagnostico_falhas": [],
        "diagnostico_decisoes": [],
        "diagnostico_servicos": {},
        "falhas_consecutivas_execucao": {},
        "ultimas_entradas": [],
        "ultima_intencao": "",
        "ultimo_alvo": "",
        "ultimo_app_janela": "",
        "ultimo_site_aba": "",
        "ultima_pasta": "",
        "ultimo_arquivo": "",
        "ultimo_caminho_arquivo": "",
        "ultimo_dispositivo_iot": "",
        "ultimo_ambiente_iot": "",
        "ultimo_estado_iot": None,
        "musica_atual_titulo": "",
        "musica_atual_url": "",
        "musica_atual_status": "",
        "musica_atual_ts": 0.0,
        "conteudo_atual": {},
        "ultima_decisao_semantica": {},
        "aprendizado_continuidade": {
            "preferencias_conflito": {},
            "preferencias_operacao": {},
            "correcoes_alvo": {},
            "correcoes_parametros": {},
            "correcoes": [],
        },
        "correcao_interpretacao_pendente": {},
        "historico_correcoes_interpretacao": [],
        "consciencia_temporal": estado_temporal_inicial(),
        "ultima_estrutura_arquivo_params": {},
        "ultima_estrutura_arquivo_ts": 0.0,
        "ultimo_escopo": "",
        "ultima_habilidade": "",
        "ultima_resposta": "",
        "direcao_fala_atual": {},
        "historico_direcao_fala": [],
        "nome_usuario": "",
        "ultima_afirmacao": "",
        "ultima_pergunta": "",
        "ultima_opiniao": "",
        "ultima_brincadeira": "",
        "resposta_esperada": "",
        "assunto_da_fala": "",
        "emocao_da_fala": "",
        "emocao_usuario": "",
        "emocao_usuario_intensidade": 0,
        "emocao_usuario_alvo": "",
        "emocao_usuario_pedido_implicito": "",
        "emocao_usuario_necessidade_acao": False,
        "emocao_usuario_texto": "",
        "emocao_usuario_ts": 0.0,
        "continuidade_fala_ts": 0.0,
        "ultima_acao_status": "",
        "ultima_acao_reexecutavel": False,
        "ultima_acao_intent": "",
        "ultima_acao_params": {},
        "ultima_acao_origem": "",
        "ultima_acao_texto": "",
        "ultima_acao_confirmada": None,
        "ultima_acao_ok": None,
        "ultima_acao_alvo": "",
        "ultima_acao_detalhe": "",
        "ultima_acao_ts": 0.0,
        "ultima_promessa_tipo": "",
        "ultima_promessa_texto": "",
        "ultima_promessa_alvo": "",
        "ultima_promessa_conteudo": "",
        "ultima_promessa_ts": 0.0,
        "oferta_pendente": {},
        "pendencia_atual": {},
        "continuidade_geral": estado_continuidade_geral_inicial(),
        "ultima_pendencia_encerrada": {},
        "preferencias_musicais": {"artistas": {}, "faixas": {}, "estilos": {}},
        "alvo_corrigido": "",
        "alvo_corrigido_ts": 0.0,
        "ultima_reparacao_alvo_anterior": "",
        "ultima_reparacao_alvo_novo": "",
        "ultima_reparacao_tipo": "",
        "ultima_reparacao_ts": 0.0,
        "pergunta_aberta_texto": "",
        "pergunta_aberta_topico": "",
        "pergunta_aberta_origem": "",
        "pergunta_aberta_tipo": "",
        "pergunta_aberta_proposito": "",
        "pergunta_aberta_resposta_esperada": "",
        "pergunta_aberta_ts": 0.0,
        "foco_vivo_tipo": "",
        "foco_vivo_alvo": "",
        "foco_vivo_topico": "",
        "foco_vivo_habilidade": "",
        "foco_vivo_intencao": "",
        "foco_vivo_texto": "",
        "foco_vivo_resposta": "",
        "foco_vivo_ts": 0.0,
        "foco_conversacional_tipo": "",
        "foco_conversacional_alvo": "",
        "foco_conversacional_topico": "",
        "foco_conversacional_habilidade": "",
        "foco_conversacional_intencao": "",
        "foco_conversacional_texto": "",
        "foco_conversacional_resposta": "",
        "foco_conversacional_escopo": "",
        "foco_conversacional_ts": 0.0,
        "foco_operacional_tipo": "",
        "foco_operacional_alvo": "",
        "foco_operacional_topico": "",
        "foco_operacional_habilidade": "",
        "foco_operacional_intencao": "",
        "foco_operacional_texto": "",
        "foco_operacional_resposta": "",
        "foco_operacional_escopo": "",
        "foco_operacional_ts": 0.0,
        "focos_por_dominio": {},
        "topico_explicito_atual": "",
        "topico_explicito_origem": "",
        "topico_explicito_ts": 0.0,
        "assunto_estruturado_atual": {},
        "registro_semantico": estado_registro_semantico_inicial(),
        "perfil_proatividade": {},
        "presenca_contextual": {
            "versao": 1,
            "historico": [],
            "ultima_emissao": {},
            "atividade": {},
            "contadores": {},
        },
        "iniciativa_autonoma": {
            "versao": 1,
            "modo": "sombra",
            "niveis": {},
            "historico": [],
            "contadores": {},
            "ultima_decisao": {},
        },
        "ts": 0.0,
    }
